QT.quickcontrols2macosstyleimpl_private.VERSION = 6.7.2
QT.quickcontrols2macosstyleimpl_private.name = QtQuickControls2MacOSStyleImpl
QT.quickcontrols2macosstyleimpl_private.module =
QT.quickcontrols2macosstyleimpl_private.libs = $$QT_MODULE_LIB_BASE
QT.quickcontrols2macosstyleimpl_private.includes = $$QT_MODULE_INCLUDE_BASE/QtQuickControls2MacOSStyleImpl/6.7.2 $$QT_MODULE_INCLUDE_BASE/QtQuickControls2MacOSStyleImpl/6.7.2/QtQuickControls2MacOSStyleImpl
QT.quickcontrols2macosstyleimpl_private.frameworks = 
QT.quickcontrols2macosstyleimpl_private.depends = quickcontrols2macosstyleimpl
QT.quickcontrols2macosstyleimpl_private.uses = 
QT.quickcontrols2macosstyleimpl_private.module_config = v2 internal_module
QT.quickcontrols2macosstyleimpl_private.enabled_features = 
QT.quickcontrols2macosstyleimpl_private.disabled_features = 
